version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10.x
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket cloudross-dev --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml