version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket cloudross-dev --output-template-file outputTemplate.yaml
artifacts:
  files:
    - template.yml
    - outputTemplate.yaml

